language: generic

dist: xenial

os:
  - linux
  - osx

smalltalk:
  - Pharo-6.0
  
env:
- ARCH="i386"


before_install:
  - |
       # Otherwise build on OSX stucks at unknown fingerprint question
       echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
       
       declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/$GITHUB_SSH_FILE)"
       # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       openssl aes-256-cbc \
         -K $encrypted_b54d1cff7fb3_key \
         -iv $encrypted_b54d1cff7fb3_iv \
         -in ".travis/travis_id_rsa.enc" \
         -out "$SSH_FILE" -d
         
       # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       
       # Enable SSH authentication
       
       chmod 600 "$SSH_FILE" \
         && printf "%s\n" \
              "Host github.com" \
              "  IdentityFile $SSH_FILE" \
              "  LogLevel ERROR" >> ~/.ssh/config
              
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo dpkg --add-architecture i386;
      sudo apt-get update;
      export PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig/;
      
      echo "Installing c++ libraries";
      sudo apt install libstdc++6:i386;
      
      echo "Installing GTK-2.0...";
      sudo apt-get install libgtk2.0-0:i386;

      echo "Installing GTK-3.0...";
      sudo apt-get install libgtk-3-0:i386;
    fi

install: 
  - ./scripts/get
    
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$ARCH" == "i386" ]]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
    fi
    
script:
  - ./pharo Pharo.image test --junit-xml-output "Bloc-.*"
  - ./pharo Pharo.image eval --save "SystemSettingsPersistence cleanUp"
